server:
  port: 8008
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: root
    url: jdbc:mariadb://localhost:3306/final
    username: root
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 150MB
      max-request-size: 180MB

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*-mapping.xml